@RestCatalogService.WebApi_HostAddress = http://localhost:5138

###  
# Add a new Item

POST {{RestCatalogService.WebApi_HostAddress}}/api/items
Content-Type: application/json
Accept: application/json

{
  "name": "My New Category 2",
  "categoryIds": [
    "11111111-1111-1111-1111-111111111111",
    "11111111-1111-1111-1111-111111111113"
  ]
}
