@RestCatalogService.WebApi_HostAddress = http://localhost:5138

###  
# List all categories

GET {{RestCatalogService.WebApi_HostAddress}}/api/categories
Content-Type: application/json
Accept: application/json
